-- SQL Project 1: E-Commerce Sales Analysis

-- 1. Total Sales
SELECT SUM(SALES) AS TOTAL_SALES
FROM ORDERS;

-- 2. Average Sales
SELECT AVG(SALES) AS AVERAGE_SALES
FROM ORDERS;

-- 3. Highest Sale
SELECT MAX(SALES) AS HIGHEST_SALE
FROM ORDERS;

-- 4. Lowest Sale
SELECT MIN(SALES) AS LOWEST_SALE
FROM ORDERS;

-- 5. Total Orders
SELECT COUNT(*) AS TOTAL_ORDERS
FROM ORDERS;

-- 6. Customer-wise Sales
SELECT CUSTOMER_ID, SUM(SALES) AS TOTAL_SALES
FROM ORDERS
GROUP BY CUSTOMER_ID;

-- 7. Category-wise Sales
SELECT P.CATEGORY, SUM(O.SALES) AS TOTAL_SALES
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY;

-- 8. Category-wise Order Count
SELECT P.CATEGORY, COUNT(*) AS ORDER_COUNT
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY;

-- 9. Highest to Lowest Sales
SELECT *
FROM ORDERS
ORDER BY SALES DESC;

-- 10. Top 1 Order
SELECT *
FROM ORDERS
ORDER BY SALES DESC
LIMIT 1;

-- 11. Sales Above 10,000
SELECT *
FROM ORDERS
WHERE SALES > 10000
ORDER BY SALES DESC;

-- 12. Customers with Total Sales Above 30,000
SELECT CUSTOMER_ID, SUM(SALES) AS TOTAL_SALES
FROM ORDERS
GROUP BY CUSTOMER_ID
HAVING SUM(SALES) > 30000;

-- 13. Customer + Product + Sales
SELECT C.NAME, P.PRODUCT_NAME, O.SALES
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID;

-- 14. Top Customer
SELECT C.NAME, SUM(O.SALES) AS TOTAL_SALES
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.NAME
ORDER BY TOTAL_SALES DESC
LIMIT 1;

-- 15. Top Product
SELECT P.PRODUCT_NAME, SUM(O.SALES) AS TOTAL_SALES
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 1;

-- 16. Top Category
SELECT P.CATEGORY, SUM(O.SALES) AS TOTAL_SALES
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_SALES DESC
LIMIT 1;

-- 17. City-wise Sales
SELECT C.CITY, SUM(O.SALES) AS TOTAL_SALES
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CITY
ORDER BY TOTAL_SALES DESC;

-- 18. Electronics Sales
SELECT SUM(O.SALES) AS ELECTRONICS_SALES
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE P.CATEGORY = 'Electronics';

-- 19. Customers with Total Sales Above 30,000
SELECT C.NAME, SUM(O.SALES) AS TOTAL_SALES
FROM ORDERS O
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.NAME
HAVING SUM(O.SALES) > 30000
ORDER BY TOTAL_SALES DESC;

-- 20. Top 3 Products
SELECT P.PRODUCT_NAME, SUM(O.SALES) AS TOTAL_SALES
FROM ORDERS O
JOIN PRODUCTS P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 3;